/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/agent/shareholdersReview': RouteRecordInfo<'/agent/shareholdersReview', '/agent/shareholdersReview', Record<never, never>, Record<never, never>>,
    '/business/manage': RouteRecordInfo<'/business/manage', '/business/manage', Record<never, never>, Record<never, never>>,
    '/finance/manage': RouteRecordInfo<'/finance/manage', '/finance/manage', Record<never, never>, Record<never, never>>,
    '/merchants/manage': RouteRecordInfo<'/merchants/manage', '/merchants/manage', Record<never, never>, Record<never, never>>,
    '/redirect/error': RouteRecordInfo<'/redirect/error', '/redirect/error', Record<never, never>, Record<never, never>>,
    '/redirect/register': RouteRecordInfo<'/redirect/register', '/redirect/register', Record<never, never>, Record<never, never>>,
    '/redirect/sign-in': RouteRecordInfo<'/redirect/sign-in', '/redirect/sign-in', Record<never, never>, Record<never, never>>,
    '/setting/menus': RouteRecordInfo<'/setting/menus', '/setting/menus', Record<never, never>, Record<never, never>>,
  }
}
