/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/redirect/register': RouteRecordInfo<'/redirect/register', '/redirect/register', Record<never, never>, Record<never, never>>,
    '/redirect/sign-in': RouteRecordInfo<'/redirect/sign-in', '/redirect/sign-in', Record<never, never>, Record<never, never>>,
    '/redirect/unauthorized': RouteRecordInfo<'/redirect/unauthorized', '/redirect/unauthorized', Record<never, never>, Record<never, never>>,
    '/setting/': RouteRecordInfo<'/setting/', '/setting', Record<never, never>, Record<never, never>>,
    '/setting/router': RouteRecordInfo<'/setting/router', '/setting/router', Record<never, never>, Record<never, never>>,
    '/setting/system': RouteRecordInfo<'/setting/system', '/setting/system', Record<never, never>, Record<never, never>>,
  }
}
